#!/usr/bin/env bash
#
# install.sh — Install upstream fakeymacs (smzht/fakeymacs) into a Keyhac directory,
# and generate a thin `config_personal.py` loader that delegates each section to:
#   1) upstream pristine sample `_config_personal.py` (runtime read)
#   2) overlay custom file `overlay/config_personal_custom.py` (this repo)
#
# Usage:
#   ./install.sh <KEYHAC_DIR>
#
# Install policy:
#   - config.py             : 常に上書き (fakeymacs本体) — 既存は .bak.<TS>
#   - fakeymacs_extensions/ : 常に上書き (fakeymacs本体) — 既存は .bak.<TS>
#   - keyhac.bat            : 常に上書き (起動ラッパー) — 既存は .bak.<TS>
#   - _config_personal.py   : 常に上書き (upstream サンプル; loader が runtime で読む)
#   - _config_parameter.py  : 常に上書き (upstream 全パラメータ参照ドキュメント)
#   - config_personal.py    : 常に再生成 (auto-generated loader)
#                              既存は .bak.<TS> へ退避。 独自設定は overlay/ へ移行する。
#
# 全操作を <KEYHAC_DIR>/install_fakeymacs.log にログ出力する。

set -euo pipefail

REPO_URL="${FAKEYMACS_REPO:-https://github.com/smzht/fakeymacs.git}"

if [ $# -lt 1 ] || [ -z "${1:-}" ]; then
    echo "Usage: $0 <KEYHAC_DIR>" >&2
    echo "  KEYHAC_DIR : keyhac.exe を含むディレクトリ" >&2
    exit 2
fi
KEYHAC_DIR="$1"
TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
LOG_FILE="${KEYHAC_DIR}/install_fakeymacs.log"
WORK_DIR=""

# このスクリプト自身の置かれているディレクトリ (= setup_fakeymacs repo の root)
SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Python が読めるパス形式に変換 (forward slash; Windows でも有効)
OVERLAY_PERSONAL="$(cygpath -m "$SELF_DIR")/overlay/config_personal_custom.py"

cleanup() {
    if [ -n "$WORK_DIR" ] && [ -d "$WORK_DIR" ]; then
        rm -rf "$WORK_DIR"
    fi
}
trap cleanup EXIT

log() {
    printf '[%s] %s\n' "$(date +%H:%M:%S)" "$*" | tee -a "$LOG_FILE"
}

abort() {
    echo "ERROR: $*" >&2
    exit 1
}

size_of() {
    if [ -d "$1" ]; then
        du -sh "$1" 2>/dev/null | awk '{print $1}'
    elif [ -f "$1" ]; then
        local b
        b=$(stat -c%s "$1" 2>/dev/null || wc -c <"$1")
        echo "${b}B"
    else
        echo "?"
    fi
}

# --- 1. ターゲット検証 -------------------------------------------------------
[ -d "$KEYHAC_DIR" ]            || abort "Keyhac directory not found: $KEYHAC_DIR"
[ -f "$KEYHAC_DIR/keyhac.exe" ] || abort "keyhac.exe not found in $KEYHAC_DIR (target doesn't look like a Keyhac install)"

log "===== fakeymacs install: ${TIMESTAMP} ====="
log "source         : $REPO_URL"
log "target         : $KEYHAC_DIR"
log "overlay custom : $OVERLAY_PERSONAL"

# --- 2. upstream を一時ディレクトリに clone ---------------------------------
WORK_DIR="$(mktemp -d -t fakeymacs-install-XXXXXX)"
log "cloning into $WORK_DIR ..."
if ! git clone --depth 1 "$REPO_URL" "$WORK_DIR/fakeymacs" >"$WORK_DIR/clone.log" 2>&1; then
    cat "$WORK_DIR/clone.log" >&2
    abort "git clone failed: $REPO_URL"
fi
SRC="$WORK_DIR/fakeymacs"
SRC_SHA="$(cd "$SRC" && git rev-parse --short HEAD)"
log "cloned commit  : $SRC_SHA"

# --- 3. install ヘルパ -------------------------------------------------------
install_overwrite() {
    local src="$1" name="$2" dest="$KEYHAC_DIR/$2"
    [ -e "$src" ] || abort "missing in upstream: $name"

    if [ -e "$dest" ]; then
        if [ -f "$src" ] && [ -f "$dest" ] && cmp -s "$src" "$dest"; then
            log "  unchanged : $name"
            return
        fi
        local backup="${dest}.bak.${TIMESTAMP}"
        mv "$dest" "$backup"
        log "  OVERWRITE : $name  ($(size_of "$backup") -> $(size_of "$src"))  backup: $(basename "$backup")"
    else
        log "  new       : $name  ($(size_of "$src"))"
    fi
    cp -r "$src" "$dest"
}

# --- 4. インストール (upstream pristine) ------------------------------------
install_overwrite "$SRC/config.py"             "config.py"
install_overwrite "$SRC/fakeymacs_extensions"  "fakeymacs_extensions"
install_overwrite "$SRC/keyhac.bat"            "keyhac.bat"
install_overwrite "$SRC/_config_personal.py"   "_config_personal.py"
install_overwrite "$SRC/_config_parameter.py"  "_config_parameter.py"

# --- 5. config_personal.py loader を自動生成 ---------------------------------
# upstream config.py の readConfigPersonal("[section-XXX]") を grep して
# 現バージョンが exec する全 section 名を抽出し、 loader を構築する。
generate_loader() {
    local custom_path="$1"
    local sections
    sections=$(grep -oE 'readConfigPersonal\("\[section-[a-zA-Z0-9_-]+\]"' "$SRC/config.py" \
               | grep -oE 'section-[a-zA-Z0-9_-]+' \
               | awk '!seen[$0]++')
    [ -n "$sections" ] || abort "no readConfigPersonal sections found in upstream config.py"

    cat <<HEADER
# -*- mode: python; coding: utf-8 -*-
#
# AUTO-GENERATED by setup_fakeymacs/install.sh — DO NOT EDIT.
# Regenerated on every install.sh run.
#
# Custom settings belong in:
#   ${custom_path}
#
# For each section that fakeymacs's config.py exec's, this loader pulls
# and exec's, in order:
#   1. the corresponding section from _config_personal.py (upstream pristine sample)
#   2. the corresponding section from the overlay custom file (your additions)
# So upstream sample updates flow through automatically (the loader does NOT
# embed upstream content — it reads _config_personal.py at runtime).
HEADER

    local is_first=1
    while IFS= read -r section; do
        printf '\n# [%s]\n' "$section"
        if [ "$is_first" = 1 ]; then
            cat <<HELPERS
import re as _re, builtins as _b, os.path as _p
def _fmx_upstream(s):
    path = _p.join(dataPath(), "_config_personal.py")
    if not _p.exists(path): return
    with open(path, encoding="utf-8-sig") as f: src = f.read()
    m = _re.search(rf"(#\s\[{_re.escape(s)}\].*?)(#\s\[section-|\Z)", src, _re.DOTALL)
    if m: exec(m.group(1), globals())
def _fmx_custom(s):
    path = r"${custom_path}"
    if not _p.exists(path): return
    with open(path, encoding="utf-8-sig") as f: src = f.read()
    m = _re.search(rf"(#\s\[{_re.escape(s)}\].*?)(#\s\[section-|\Z)", src, _re.DOTALL)
    if m: exec(m.group(1), globals())
_b._fmx_upstream = _fmx_upstream
_b._fmx_custom   = _fmx_custom
HELPERS
            is_first=0
        fi
        printf '_fmx_upstream("%s")\n' "$section"
        printf '_fmx_custom("%s")\n'   "$section"
    done <<< "$sections"
}

TMP_LOADER="$WORK_DIR/config_personal.py"
generate_loader "$OVERLAY_PERSONAL" > "$TMP_LOADER"

# section 数を log に残す (生成内容の検証用)
SECTION_COUNT=$(grep -c '^_fmx_upstream' "$TMP_LOADER")
log "generated config_personal.py loader: ${SECTION_COUNT} sections"

install_overwrite "$TMP_LOADER" "config_personal.py"

log "===== install complete (upstream $SRC_SHA) ====="
log ""
log "Customize your settings here:"
log "  $OVERLAY_PERSONAL"
